#!/usr/bin/env python3
# -*- coding: utf-8 -*-

''' 
a test module 
to void input many lines in a interactive environment
'''

__author__ = 'Sherplus'


import inspect
print(inspect.getfile(inspect.currentframe())) # script filename (usually with path)
print("-- Generated by script: {} --\n\n\n".format(inspect.getfile(inspect.currentframe()))) # script directory

